const data = [
    {
      name: "Jan 2020",
      past: 0, 
      pastInfo: "• Completed Bachelor of Accountancy",
      path1Info: "",
      path2Info: "",
    },
    {
        name: "Aug 2020",
        past: 3,
        pastInfo: "• Started working as Junior Investment Banker",
        path1Info: "",
        path2Info: "",
      },
    {
        name: "Jan 2021",
        past: 6,
        pastInfo: "• Certificate in Xero",
        path1Info: "",
        path2Info: "",
      },
    {
        name: "Aug 2021",
        past: 15,
        pastInfo: "• Advanced Certificate in Xero",
        path1Info: "",
        path2Info: "",
      },
    {
        name: "Jan 2022",
        past: 25,
        pastInfo: "• Company internal Promotion",
        path1Info: "",
        path2Info: "",
      },
      {
        name: "Today (Dec 2022)",
        past: 30,
        pastInfo: "Your career today. You can choose Career path 1 or Career path 2",
        path1: 30,
        path1Info: "",
        path2: 30,
        path2Info: "",
      },
    {
        name: "Jan 2023",
        pastInfo: " ",
        path1: 32,
        path1Info: "• Company internal Promotion",
        path2Info: "• Company internal Promotion",
        path2: 35,
      },
    {
        name: "Aug 2023",
        pastInfo: "",
        path1Info: "• registered as Chartered Accountant (CA)",
        path1: 40,
        path2Info: "• registered as Chartered Accountant (CA)",
        path2: 43,
      },
      {
        name: "Jan 2024",
        pastInfo: "",
        path1Info: "• Promotion to Data Analyst",
        path1: 50,
        path2Info: "• Promotion to Data Analyst",
        path2: 45,
      },
      {
        name: "Aug 2024",
        pastInfo: "",
        path1Info: "• Changed Companies",
        path1: 45,
        path2Info: "• Changed Companies",
        path2: 50,
      },
      {
        name: "Jan 2025",
        pastInfo: " ",
        path1: 55,
        path1Info: "path 1: Certifiate 1",
        path2: 60,
        path2Info: "path 2: Certifiate 2",
      },
      {
        name: "Aug 2025",
        pastInfo: " ",
        path1: 65,
        path1Info: "path 1: Senior Financial Management Accountant",
        path2: 69,
        path2Info: "path 2: Certifiate 3",
      },
      {
        name: "Jan 2026",
        pastInfo: " ",
        path1: 75,
        path1Info: "path 1: Certifiate 4",
        path2: 80,
        path2Info: "path 2: Master of Accounting",
      },
      {
        name: "Aug 2026",
        pastInfo: " ",
        path1: 85,
        path1Info: "path 1: Private Equity Partner",
        path2: 85,
        path2Info: "path 2: Private Equity Partner",
      },
      {
        name: "Jan 2027",
        pastInfo: " ",
        path1: 100,
        path1Info: "path 1: Managing Director",
        path2: 95,
        path2Info: "path 2: Master of Accounting",
      },
      {
        name: "Aug 2027",
        pastInfo: " ",
        path1Info: "",
        path2: 100, 
        path2Info: "path 2: Managing Director",
      },
  ];

  export default data