const data2 = [
  {
    name: "Jan 2018",
    past: 0, 
    pastInfo: "• Completed Bachelor of Accountancy",
    path1Info: "",
    path2Info: "",
  },
  {
      name: "Aug 2018",
      past: 5,
      pastInfo: "• Started working as Financial Accountant",
      path1Info: "",
      path2Info: "",
    },
  {
      name: "Jan 2019",
      past: 8,
      pastInfo: "• Certificate in Xero",
      path1Info: "",
      path2Info: "",
    },
  {
      name: "Aug 2019",
      past: 17,
      pastInfo: "• Advanced Certificate in Xero",
      path1Info: "",
      path2Info: "",
    },
  {
      name: "Jan 2020",
      past: 20,
      pastInfo: "• Company internal Promotion",
      path1Info: "",
      path2Info: "",
    },
  {
      name: "Aug 2020",
      past: 23,
      pastInfo: "• Changed Company",
      path1Info: "",
      path2Info: "",
    },
  {
      name: "Jan 2021",
      past: 30,
      pastInfo: "• Company internal Promotion",
      path1Info: "",
      path2Info: "",
    },
  {
      name: "Aug 2021",
      past: 31,
      pastInfo: "• registered as Chartered Accountant (CA)",
      path1Info: "",
      path2Info: "",
    },
    {
      name: "Jan 2022",
      past: 34,
      pastInfo: "• Promotion to Senior Accountant",
      path1Info: "",
      path2Info: "",
    },
    {
      name: "Today (Nov 2022)",
      past: 40,
      pastInfo: "Your career today. You can choose Career path 1 or Career path 2",
      path1: 40,
      path1Info: "",
      path2: 40,
      path2Info: "",
    },
    {
      name: "Jan 2023",
      pastInfo: " ",
      path1: 45,
      path1Info: "path 1: Certifiate 1",
      path2: 58,
      path2Info: "path 2: Certifiate 2",
    },
    {
      name: "Aug 2023",
      pastInfo: " ",
      path1: 60,
      path1Info: "path 1: Senior Financial Management Accountant",
      path2: 69,
      path2Info: "path 2: Certifiate 3",
    },
    {
      name: "Jan 2024",
      pastInfo: " ",
      path1: 65,
      path1Info: "path 1: Certifiate 4",
      path2: 72,
      path2Info: "path 2: Master of Accounting",
    },
    {
      name: "Aug 2024",
      pastInfo: " ",
      path1: 85,
      path1Info: "path 1: Finance Manager",
      path2: 85,
      path2Info: "path 2: Finance Manager",
    },
    {
      name: "Jan 2025",
      pastInfo: " ",
      path1: 95,
      path1Info: "path 1: Financial Controller",
      path2: 100,
      path2Info: "path 2: Master of Accounting",
    },
    {
      name: "Aug 2025",
      pastInfo: " ",
      path1: 100,
      path1Info: "", 
      path2Info: "path 2: Financial Controller",
    },
];

export default data2