import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React from 'react'
import { signIn, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data: session } = useSession()
  console.log(session)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col gap-2 items-center justify-center p-4">
        <div className="text-2xl font-semibold">Welcome to Dacreed New Horizons</div>
        <p>your intelligent career journey mapping tool</p>
        <p>Create an account to begin</p>
        <button onClick={() => signIn('google', {callbackUrl: 'http://localhost:3000/dashboard'})} className="px-5 py-2 bg-[#1848C8] hover:bg-[#AFC3FF] text-white rounded-full">
          Sign up with Google
        </button>
        <p>Already have an account?</p>
        <button onClick={() => signIn(undefined, {callbackUrl: 'http://localhost:3000/dashboard' })} className="px-5 py-2 bg-[#1848C8] hover:bg-[#AFC3FF] text-white rounded-full">
          Sign in
        </button>

      </main>
    </>
  );
};

export default Home;


