import Head from "next/head";
import Link from "next/link";
import * as d3 from "d3";
import OurTree from "../components/innerCircleGraph/OurTree";

const prototypeS1 = () => {
  return (
    <>
        <Head>
        <title>prototype S 1</title>
        <meta name="prototype 1" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
<main className='mx-auto my-12 max-w-full'>
  
<div className="flex justify-center">
<h2 className="text-2xl font-semibold">Thank you for choosing this Prototype</h2>
</div>

<div className="flex justify-center">
<p>Click Start to see your career development options</p>
</div>

<div className="flex justify-center my-12 max-h-full" >
<OurTree/>
</div>

<div className="flex justify-center my-12">
<Link href={"/dashboard"} >
<button className="px-5 py-2 bg-[#1848C8] hover:bg-[#AFC3FF] text-white rounded-full">
 back to dashboard
</button>
</Link>
</div>

</main>
      
    </>
  )
}

export default prototypeS1
