const sankeyData3 = {
    nodes: [
      { name: "Junior Investment Banker"},
      { name: "Investment Banking Analyst" },
      { name: "Finanical Advisor" },
      { name: "Data Analyst" },
      { name: "Senior Finanical Advisor" },
      { name: "Accounting Manager" },
      { name: "Finance Manager" },
      { name: "Managing Director" },
      { name: "Vice President" },
      { name: "Senior Vice President" },
      { name: "Chief Financial Officer" },
    ],
    links: [
      { source: 0, target: 4, value: 26 },
      { source: 0, target: 2, value: 18 },
      { source: 0, target: 3, value: 28 },
      { source: 1, target: 2, value: 8 },
      { source: 1, target: 3, value: 20 },
      { source: 1, target: 4, value: 20 },
      { source: 1, target: 6, value: 48 },
      { source: 2, target: 5, value: 33 },
      { source: 2, target: 3, value: 8 },
      { source: 2, target: 4, value: 29 },
      { source: 2, target: 6, value: 31 },
      { source: 3, target: 5, value: 25 },
      { source: 3, target: 7, value: 45 },
      { source: 4, target: 8, value: 58 },
      { source: 4, target: 5, value: 4 },
      { source: 4, target: 10, value: 65 },
      { source: 5, target: 7, value: 22 },
      { source: 5, target: 8, value: 52 },
      { source: 5, target: 9, value: 25 },
      { source: 6, target: 9, value: 39 },
      { source: 6, target: 10, value: 32 },
      { source: 6, target: 7, value: 15 },
      { source: 6, target: 8, value: 11 },
    ]
  };

  export default sankeyData3;